# Generated by Django 5.1.4 on 2024-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_spec',
            field=models.CharField(default='physician', max_length=200),
        ),
    ]
